const projects = [
  {
    id: 1,
    title: "Glutenfree",
    category: "UX/UI Design",
    year: 2017,
    image: "https://i.postimg.cc/RFJm5VCb/glutenfree2.png",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 2,
    title: "Recycler",
    category: "UX/UI Design",
    year: 2021,
    image: "https://i.postimg.cc/gkHWP7dd/recyler1.png",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 3,
    title: "Homepal",
    category: "UX/UI Design",
    year: 2021,
    image: "https://i.postimg.cc/MGNkD200/HOMEPAL.png",
    isComplete: false,
    isInTeam: false,
  },
  {
    id: 4,
    title: "Happy Hour",
    category: "Packaging Design",
    year: 2020,
    image: "https://i.postimg.cc/Wb2y01LL/COTTIFRAG.jpg",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 5,
    title: "FILA Packaging Award",
    category: "Packaging Design",
    year: 2020,
    image: "https://i.postimg.cc/pL3kc27d/WOMAN.jpg",
    isComplete: true,
    isInTeam: true,
  },
  {
    id: 6,
    title: "Conservatorio A. Corelli",
    category: "Brand Design",
    year: 2020,
    image: "https://i.postimg.cc/D0zqyDDD/STATIONERY.jpg",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 7,
    title: "Lo Studente in Crisi",
    category: "Brand Design",
    year: 2020,
    image: "https://i.postimg.cc/rwvXG2N1/mug.jpg",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 8,
    title: "Didot: type specimen",
    category: "Layout Design",
    year: 2019,
    image: "https://i.postimg.cc/ZR4QjbBd/BOOK.jpg",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 9,
    title: "Gorghitondi",
    category: "Packaging Design",
    year: 2020,
    image: "https://i.postimg.cc/Y0SsKdx2/BIANCO02.jpg",
    isComplete: true,
    isInTeam: true,
  },
  {
    id: 10,
    title: "Didot: type specimen",
    category: "Layout Design",
    year: 2019,
    image: "https://i.postimg.cc/qBZm6XLn/DIDOT06.jpg",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 11,
    title: "Didot: type specimen",
    category: "Layout Design",
    year: 2019,
    image: "https://i.postimg.cc/sf8cgfj4/DIDOT03.jpg",
    isComplete: true,
    isInTeam: false,
  },
];

export default projects;
