import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import MainLayout from "@/layouts/mainlayout/MainLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <main className={styles.main}></main>
      </MainLayout>
    </>
  );
}
