const projects = [
  {
    id: 1,
    title: "Glutenfree",
    category: "UX/UI Design",
    year: 2017,
    image: "https://bit.ly/3WrFda2",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 2,
    title: "Recycler",
    category: "UX/UI Design",
    year: 2021,
    image: "https://bit.ly/3sY007O",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 3,
    title: "Homepal",
    category: "UX/UI Design",
    year: 2021,
    image: "https://bit.ly/3FIrd5P",
    isComplete: false,
    isInTeam: false,
  },
  {
    id: 4,
    title: "Happy Hour",
    category: "Packaging Design",
    year: 2020,
    image: "https://bit.ly/3zJ3Mpg",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 5,
    title: "FILA Packaging Award",
    category: "Packaging Design",
    year: 2020,
    image: "https://bit.ly/3DYXhkw",
    isComplete: true,
    isInTeam: true,
  },
  {
    id: 6,
    title: "Conservatorio A. Corelli",
    category: "Brand Design",
    year: 2020,
    image: "https://bit.ly/3fvLQYe",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 7,
    title: "Lo Studente in Crisi",
    category: "Brand Design",
    year: 2020,
    image: "https://bit.ly/3h9Equi",
    isComplete: true,
    isInTeam: false,
  },
  {
    id: 8,
    title: "Didot: type specimen",
    category: "Layout Design",
    year: 2019,
    image: "https://bit.ly/3h7G5jV",
    isComplete: true,
    isInTeam: false,
  },
];

export default projects;
